### PR TITLE
Update table

### PR DESCRIPTION
**Pull request by jpellegrini**
There are some new SRFIs, and both STklos and unsyntax had new SRFIs added to their dev branches.

### CODE REVIEW

**Comment by jpellegrini** [comment]
But... Now that I have made the PR I notices there's something wrong in unsyntax's list of SRFIs. See the numbers...
And it seems that one of the supported SRFIs is gone (?)

**Comment by lassik** [comment]
Thanks! Yes, there's something wrong with the regexp we are using to grep for unsyntax SRFIs; have to edit manually for now. Can you push another commit to do that?

**Comment by jpellegrini** [comment]
Done!

**Comment by lassik** [comment]
Thanks!

**Pull request merged**
